### PR TITLE
Android build with precompiled binaries, build config additions.

### PR DESCRIPTION
**Pull request by Dyrewulfe**
Details are in the commit message. I also updated the tools and minimum api configuration, due to api 14 being no longer supported. And Google likes to pull a mafia and make older toolkits disappear, so this will give a little extra leeway before it has to be updated again.

### CODE REVIEW

**Comment by Dyrewulfe** [comment]
I'm also working on a unified dependencies repository to go along with this, but it's a bit of a mess right now and will take a few days  of work before it's ready to go live.

**Comment by Dyrewulfe** [comment]
Got some sleep, and with a clearer head it occurred to me that placing the dependencies in a zip file was really the better solution.

**Comment by Dyrewulfe** [comment]
Adding in automation for lua bindings, version header, and localization.

**Review by a1studmuffin — COMMENTED** [review]
Looks like there's some great changes in here, thanks! The only thing I'm not sure about is the dependencies zip. I spoke with Kevin and he suggested dependencies should be kept out of the main repo:

https://discourse.cataclysmdda.org/t/android-version/13348/276?u=a1studmuffin

I'll take a closer look on the weekend and see if anything else jumps out, cheers.

**Comment by Dyrewulfe** [comment]
Aye, I thought about the deps.zip in that regard, too.  I'm setting up a repository that will handle generating that zip file. I just need to work out some things with the gradle build.  Then we should be able to point the build script at the latest dependencies release zip on GH and just download it prebuild.  But I figured I should add it in for now to make the file easily available for people to test out the build process with prior to merging.

Edit: Oh yeah. This is coming a bit late, and I'm surprised no one has mentioned it to you yet. Setting "Use Tiles" prior to loading is no longer necessary. Tileset loading has been deferred to game start/load, so options are accessible and can be changed before they have a memory impact. While I was testing this build system, I did run into a situation where I enabled software rendering on one of my devices, and it failed. Rather than forcing the user to clear settings then re-install data, it might be a good idea to have a "Remember setting" check box, and bring up that screen each load until it's been checked.

**Comment by a1studmuffin** [comment]
Heya, I tested out the changes today under Linux (command line) and Windows (Android Studio). Awesome work! I've got a couple of minor fix requests - I'll hold off on any rebasing/changes to my PR branch until you get a chance to fix them:

1) It'd be good to update COMPILING.md to reflect these changes (basically just removing the part about fetching dependencies from other repos since it's no longer necessary)

2) It would be nice to keep this compiling under Android Studio on Windows, but the new prebuild steps break since the commands ('make', 'unzip' etc.) aren't found on that platform. I think the simplest fix would be to make those prebuild steps conditional for Linux only (https://stackoverflow.com/questions/11235614/how-to-detect-the-current-os-from-gradle), and we can leave the Windows version requiring manual prebuild steps, unless you can think of a better option?

3) I'm seeing some Gradle build warnings, should be easy enough to clean up in app\build.gradle:
`WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation'.
It will be removed at the end of 2018
WARNING: Configuration 'androidTestCompile' is obsolete and has been replaced with 'androidTestImplementation'.
It will be removed at the end of 2018
WARNING: Configuration 'androidTestApi' is obsolete and has been replaced with 'androidTestImplementation'.
It will be removed at the end of 2018
WARNING: Configuration 'testCompile' is obsolete and has been replaced with 'testImplementation'.
It will be removed at the end of 2018
WARNING: Configuration 'testApi' is obsolete and has been replaced with 'testImplementation'.
It will be removed at the end of 2018`

That's it, thanks heaps for the fixes and improvements!

Oh also, RE: the "Use tiles" checkbox and "Remember settings" option, that's an excellent idea, thanks - I've added to the todo list (though I may get around to it after the PR is accepted into mainline, we'll see.)

**Comment by Dyrewulfe** [comment]
1. I'll get to that here in a bit.

2. I had a better idea! (although mucking around with Windows was somewhat taxing of my sanity.)

3. Upon further examination, these warnings are related to dependencies we simply don't need or have use for in the project. We're not running a test suite on Java code, so I dropped 'em.

**Comment by a1studmuffin** [comment]
Looks like my Android Branch just got PR'd into mainline so I guess easiest thing to do is rebase your changes onto master and send them a PR instead?

**Pull request closed without merging**
